/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class TTSMessageHandler */

#ifndef _Included_TTSMessageHandler
#define _Included_TTSMessageHandler

#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     TTSMessageHandler
 * Method:    TTSSpeak
 * Signature: (Ljava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_com_ibm_collaboration_realtime_tts_TTSMessageHandler_TTSSpeak
  (JNIEnv *, jclass, jstring);

/*
 * Class:     com_ibm_collaboration_realtime_tts_TTSPlugin
 * Method:    TTSInit
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_com_ibm_collaboration_realtime_tts_TTSPlugin_TTSInit
  (JNIEnv *, jclass);

/*
 * Class:     com_ibm_collaboration_realtime_tts_TTSPlugin
 * Method:    TTSStop
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_com_ibm_collaboration_realtime_tts_TTSPlugin_TTSStop
(JNIEnv *, jclass, jboolean);

/*
 * Class:     com_ibm_collaboration_realtime_tts_TTSPlugin
 * Method:    TTSUninit
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_com_ibm_collaboration_realtime_tts_TTSPlugin_TTSUninit
  (JNIEnv *, jclass);

/*
 * Class:     com_ibm_collaboration_realtime_tts_TTSPlugin
 * Method:    setRuntime
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_com_ibm_collaboration_realtime_tts_TTSPlugin_setRuntime
(JNIEnv *, jclass, jint);  

/*
 * Class:     com_ibm_collaboration_realtime_tts_TTSPlugin
 * Method:    TTSInit
 * Signature: ()Z
 */
JNIEXPORT jint JNICALL Java_com_ibm_collaboration_realtime_tts_TTSPlugin_TTSDetect
(JNIEnv *, jclass, jint);  


/*
 * Class:     com_ibm_collaboration_realtime_tts_preferences_PreferenceDialog
 * Method:    GetLanguages
 * Signature: (I)[Ljava/lang/String;
 */
JNIEXPORT jobjectArray JNICALL Java_com_ibm_collaboration_realtime_tts_preferences_PreferenceDialog_GetLanguages
  (JNIEnv *, jclass, jint);

/*
 * Class:     com_ibm_collaboration_realtime_tts_preferences_PreferenceDialog
 * Method:    GetVoices
 * Signature: ()[Ljava/lang/String;
 */
JNIEXPORT jboolean JNICALL Java_com_ibm_collaboration_realtime_tts_preferences_PreferenceDialog_SetLanguageVoice
  (JNIEnv *, jclass, jint, jint, jint);

/*
 * Class:     com_ibm_collaboration_realtime_tts_TTSPlugin
 * Method:    TTSInit
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_com_ibm_collaboration_realtime_tts_TTSPlugin_TTSDialog
  (JNIEnv *, jclass, jboolean);

/*
 * Class:     com_ibm_collaboration_realtime_tts_Common
 * Method:    GetLanguages
 * Signature: (I)[Ljava/lang/String;
 */
JNIEXPORT jobjectArray JNICALL Java_com_ibm_collaboration_realtime_tts_Common_Enum
  (JNIEnv *, jclass);
  
#ifdef __cplusplus
}
#endif
#endif
